import { DEFAULT_CONFIG } from "./defaultData.js";
import { initFirebase, listenRecords, listenConfig, saveConfig, saveRecord, removeRecord } from "./firebase.js";
import { currentWeek, weekOptions, uid, formatDate, csvDownload } from "./utils.js";

const app = document.getElementById("app");
const params = new URLSearchParams(location.search);
const state = { page: params.get("page")==="checkin" ? "checkin" : "home", adminTab:"teams", formType:"team", week:currentWeek(), records:[], config:null, team:"", name:"", values:{}, search:"", editId:null };

const C=()=>state.config||DEFAULT_CONFIG, teams=()=>C().teams||[], teamRules=()=>C().teamRules||[], personalRules=()=>C().personalRules||[], activity=()=>C().activity||DEFAULT_CONFIG.activity, events=()=>C().events||[];
const teamByName=n=>teams().find(t=>t.name===n);
const allMembers=()=>teams().flatMap(t=>(t.members||[]).map(m=>({name:m,team:t.name,icon:t.icon})));
const calcScore=(type,vals)=>(type==="team"?teamRules():personalRules()).reduce((s,r)=>s+Number(vals[r.key]||0)*Number(r.points||0),0);
function daysLeft(){const end=new Date(activity().endDate+"T23:59:59"); return Math.max(0,Math.ceil((end-new Date())/86400000));}
function todayCount(){const d=new Date(); d.setHours(0,0,0,0); return state.records.filter(r=>(r.createdAt||0)>=d.getTime()).length;}
function teamRank(week=state.week){const s={};teams().forEach(t=>s[t.name]=0);state.records.forEach(r=>{if((r.recordType==="team"||!r.recordType)&&(week==="ALL"||r.week===week)&&s[r.team]!==undefined)s[r.team]+=Number(r.totalScore||0)});return Object.entries(s).map(([team,score])=>({...teamByName(team),team,score})).sort((a,b)=>b.score-a.score)}
function personRank(week=state.week){const s={};allMembers().forEach(m=>s[m.name]={score:0,team:m.team,icon:m.icon});state.records.forEach(r=>{if(r.recordType==="personal"&&(week==="ALL"||r.week===week)){if(!s[r.name])s[r.name]={score:0,team:r.team,icon:"👤"};s[r.name].score+=Number(r.totalScore||0)}});return Object.entries(s).map(([name,d])=>({name,...d})).sort((a,b)=>b.score-a.score)}
function toast(m){const el=document.createElement("div");el.className="toast";el.textContent=m;document.body.appendChild(el);setTimeout(()=>el.remove(),2400)}

function shell(content){
  app.innerHTML=`<div class="layout"><aside class="sidebar"><div class="brand"><div class="brand-logo">🐺</div><div><div class="brand-title"><b>AMR</b> 人力特攻隊</div><div class="brand-sub">${activity().subtitle}</div></div></div><div class="menu">${menu("home","🏠","首頁")}${menu("score","➕","新增積分")}${menu("rank","🏆","團隊排行")}${menu("person","👤","個人排行")}${menu("history","🕘","歷史紀錄")}${menu("qr","📅","活動簽到")}${menu("admin","⚙️","設定管理")}</div><div class="side-stat"><div class="side-label">⏱ 活動倒數</div><div class="side-value">${daysLeft()}</div></div><div class="side-stat"><div class="side-label">☆ 本週總積分</div><div class="side-value">${teamRank().reduce((a,b)=>a+b.score,0)}</div><div class="side-small">即時同步</div></div></aside><main class="main"><div class="topbar"><select class="event-pill" id="eventTop"><option>${activity().currentEvent||"本週活動"}</option>${events().map(e=>`<option>${e.name}</option>`).join("")}</select><div class="top-actions"><button class="btn green" data-page="meeting">🖥 晨會模式</button><button class="btn" data-page="admin">⚙</button><button class="btn">🐺</button></div></div>${content}<div class="footer"><span>${activity().title}｜${activity().subtitle}</span><span>🟢 即時同步　🔥 Firebase　© Team 465</span></div></main></div><nav class="mobile-nav">${mnav("home","🏠","首頁")}${mnav("score","➕","計分")}${mnav("rank","🏆","排行")}${mnav("history","📜","歷史")}${mnav("admin","⚙️","設定")}</nav>`;
  document.querySelectorAll("[data-page]").forEach(b=>b.onclick=()=>{state.page=b.dataset.page;render()});
}
const menu=(p,i,l)=>`<button class="${state.page===p?"active":""}" data-page="${p}"><span>${i}</span>${l}</button>`;
const mnav=(p,i,l)=>`<button class="${state.page===p?"active":""}" data-page="${p}"><span>${i}</span>${l}</button>`;

function renderHome(){const tr=teamRank(),pr=personRank(),top=tr[0],mvp=pr[0],last=tr[1];shell(`<div class="grid-main"><section class="hero"><div class="champ-badge">👑 本週冠軍</div><div class="champ-name">${top?.team||"尚無資料"}</div><div class="champ-score">${top?.score||0}<small> 分</small></div><div class="streak">🔥 連續領先 ${top?.score?3:0} 週</div></section><div class="stack"><div class="mini purple"><div class="mini-label">👑 MVP</div><div class="mini-name">${mvp?.name||"尚無"}</div><div class="mini-score">${mvp?.score||0} 分</div></div><div class="mini blue"><div class="mini-label">🏅 上週冠軍</div><div class="mini-name">${last?.team||"尚無"}</div><div class="mini-score">${last?.score||0} 分</div></div><div class="mini green"><div class="mini-label">☘ 今日新增</div><div class="mini-name">${todayCount()} 筆</div><div class="mini-score">即時更新</div></div></div></div><div class="two"><section class="card"><h2>🏆 團隊排行榜</h2>${rankTable(tr,"team").slice(0,5).join("")}<button class="btn gold" data-page="rank" style="width:100%;margin-top:12px">查看完整排行 →</button></section><section class="card"><h2>👤 個人排行榜</h2>${rankTable(pr,"person").slice(0,5).join("")}<button class="btn green" data-page="person" style="width:100%;margin-top:12px">查看完整排行 →</button></section></div><div class="two"><section class="card"><h2>🕘 最新紀錄</h2><div class="history">${state.records.slice(0,5).map(historyRow).join("")||`<div class="empty">尚無紀錄</div>`}</div><button class="btn blue" data-page="history" style="width:100%;margin-top:12px">查看全部紀錄 →</button></section><section class="card"><h2>⚡ 快速操作</h2><div class="quick-grid"><button class="quick btn purple" data-page="score"><span>＋</span>新增積分</button><button class="quick btn blue" data-page="history"><span>🕘</span>歷史紀錄</button><button class="quick btn green" id="exportBtn"><span>📥</span>匯出 Excel</button><button class="quick btn gold" data-page="meeting"><span>🖥</span>晨會模式</button><button class="quick btn red" data-page="qr"><span>📱</span>簽到 QR</button><button class="quick btn" data-page="admin"><span>⚙️</span>設定管理</button></div></section></div>`);bindShared();}
function bindShared(){document.querySelectorAll("[data-page]").forEach(b=>b.onclick=()=>{state.page=b.dataset.page;render()});const ex=document.getElementById("exportBtn");if(ex)ex.onclick=exportRows}
function rankTable(rows,type){const max=Math.max(...rows.map(r=>r.score),1);return rows.map((r,i)=>`<div class="row"><div class="ranknum ${i===0?"top":""}">${i+1}</div><div><div class="rname">${type==="team"?(r.icon||"")+" "+r.team:(r.icon||"👤")+" "+r.name}</div><div class="rsub">${type==="team"?"團隊":r.team}</div></div><div class="rscore">${r.score}</div></div>`)}
function historyRow(r){return `<div class="hist-row"><div><div class="hist-name">${r.name}　${r.team}</div><div class="hist-meta">${r.note||"積分紀錄"}</div></div><div class="hist-plus">+${r.totalScore||0}</div><div class="hist-time">${formatDate(r.createdAt)}</div></div>`}

function renderScore(){const rules=state.formType==="team"?teamRules():personalRules(),members=state.team?(teamByName(state.team)?.members||[]):[];shell(`<section class="card form-card"><h2>➕ 新增積分</h2><div class="tabs"><button class="tab ${state.formType==="team"?"active":""}" data-ft="team">團隊</button><button class="tab ${state.formType==="personal"?"active":""}" data-ft="personal">個人</button></div><div class="form-grid"><label class="field"><span>週次</span><select id="weekSel">${weekOptions().map(w=>`<option ${w===state.week?"selected":""}>${w}</option>`).join("")}</select></label><label class="field"><span>隊伍</span><select id="teamSel"><option value="">請選擇</option>${teams().map(t=>`<option value="${t.name}" ${t.name===state.team?"selected":""}>${t.icon} ${t.name}</option>`).join("")}</select></label></div><label class="field"><span>姓名</span><select id="nameSel" ${state.team?"":"disabled"}><option value="">請選擇</option>${members.map(m=>`<option ${m===state.name?"selected":""}>${m}</option>`).join("")}</select></label>${rules.map(ruleCounter).join("")}<div class="total"><span>本次得分</span><b>${calcScore(state.formType,state.values)} 分</b></div><button class="btn primary" style="width:100%" id="saveBtn">${state.editId?"儲存修改":"送出積分"}</button></section>`);document.querySelectorAll("[data-ft]").forEach(b=>b.onclick=()=>{state.formType=b.dataset.ft;state.values={};render()});document.getElementById("weekSel").onchange=e=>state.week=e.target.value;document.getElementById("teamSel").onchange=e=>{state.team=e.target.value;state.name="";render()};document.getElementById("nameSel").onchange=e=>state.name=e.target.value;document.querySelectorAll("[data-inc]").forEach(b=>b.onclick=()=>{state.values[b.dataset.inc]=Number(state.values[b.dataset.inc]||0)+1;render()});document.querySelectorAll("[data-dec]").forEach(b=>b.onclick=()=>{state.values[b.dataset.dec]=Math.max(0,Number(state.values[b.dataset.dec]||0)-1);render()});document.getElementById("saveBtn").onclick=submitScore}
function ruleCounter(r){return `<div class="score-item"><div><div class="score-name">${r.label}</div><div class="score-meta">+${r.points} 分 / ${r.unit}</div></div><div class="counter"><button data-dec="${r.key}">−</button><div class="num">${Number(state.values[r.key]||0)}</div><button data-inc="${r.key}">＋</button></div></div>`}
async function submitScore(){if(!state.team)return toast("請選隊伍");if(!state.name)return toast("請選姓名");const total=calcScore(state.formType,state.values);if(total<=0)return toast("請新增積分");const safe=state.week.replace(/\//g,"-").replace(/\s/g,"");await saveRecord(state.editId||`${safe}_${state.name}_${state.formType}_${Date.now()}`,{...state.values,week:state.week,team:state.team,name:state.name,recordType:state.formType,totalScore:total,note:"手動加分",createdAt:Date.now(),updatedAt:Date.now()});toast("新增成功");state.page="home";state.values={};render()}

function renderRank(){shell(`<section class="card"><h2>🏆 團隊排行榜</h2>${rankTable(teamRank(),"team").join("")}</section>`)}
function renderPerson(){shell(`<section class="card"><h2>👤 個人排行榜</h2>${rankTable(personRank(),"person").join("")}</section>`)}
function renderHistory(){shell(`<section class="card"><h2>🕘 歷史紀錄</h2><input id="search" placeholder="搜尋姓名、隊伍、週次" value="${state.search}"><div class="history" id="hist"></div></section>`);document.getElementById("search").oninput=e=>{state.search=e.target.value;drawHist()};drawHist()}
function drawHist(){const q=state.search.trim();const rows=state.records.filter(r=>!q||`${r.name} ${r.team} ${r.week}`.includes(q));document.getElementById("hist").innerHTML=rows.map(r=>`<div class="hist-row"><div><div class="hist-name">${r.name}｜${r.team}</div><div class="hist-meta">${r.week}｜${r.note||"積分紀錄"}</div></div><div class="hist-plus">+${r.totalScore||0}</div><button class="btn red" data-del="${r.id}">刪</button></div>`).join("")||`<div class="empty">尚無紀錄</div>`;document.querySelectorAll("[data-del]").forEach(b=>b.onclick=async()=>{if(confirm("確定刪除？")){await removeRecord(b.dataset.del);toast("已刪除")}})}

function checkinUrl(){const ev=events().find(e=>e.active)||events()[0]||{id:"event-main"};return `${location.origin}${location.pathname}?page=checkin&event=${ev.id}&date=${new Date().toISOString().slice(0,10)}`}
function renderQR(){const url=checkinUrl(),qr=`https://api.qrserver.com/v1/create-qr-code/?size=360x360&data=${encodeURIComponent(url)}`;shell(`<section class="card"><h2>📱 活動簽到 QR Code</h2><p class="rsub">每場活動可建立不同 QR；掃描後只簽到，不簽退，同人同場不能重複加分。</p><div class="qr-box"><img class="qr-img" src="${qr}"><div class="qr-url">${url}</div><button class="btn primary" id="copy">複製簽到連結</button></div></section>`);document.getElementById("copy").onclick=async()=>{await navigator.clipboard.writeText(url);toast("已複製")}}
function renderCheckin(){const ev=events().find(e=>e.id===params.get("event"))||events().find(e=>e.active)||events()[0]||{id:"event-main",name:"活動簽到",points:1};const members=state.team?(teamByName(state.team)?.members||[]):[];shell(`<section class="card form-card"><h2>📍 ${ev.name}</h2><p class="rsub">活動日期：${params.get("date")||new Date().toISOString().slice(0,10)}｜簽到 +${ev.points||1} 分</p><label class="field"><span>隊伍</span><select id="teamSel"><option value="">請選擇</option>${teams().map(t=>`<option value="${t.name}" ${t.name===state.team?"selected":""}>${t.icon} ${t.name}</option>`).join("")}</select></label><label class="field"><span>姓名</span><select id="nameSel" ${state.team?"":"disabled"}><option value="">請選擇</option>${members.map(m=>`<option ${m===state.name?"selected":""}>${m}</option>`).join("")}</select></label><button class="btn primary" style="width:100%" id="checkin">完成簽到 +${ev.points||1}</button></section>`);document.getElementById("teamSel").onchange=e=>{state.team=e.target.value;state.name="";render()};document.getElementById("nameSel").onchange=e=>state.name=e.target.value;document.getElementById("checkin").onclick=()=>submitCheckin(ev)}
async function submitCheckin(ev){if(!state.team)return toast("請選隊伍");if(!state.name)return toast("請選姓名");const date=params.get("date")||new Date().toISOString().slice(0,10),id=`checkin_${ev.id}_${date}_${state.name}`;if(state.records.some(r=>r.id===id))return toast("你已完成本場簽到");await saveRecord(id,{checkin:1,eventId:ev.id,eventName:ev.name,week:state.week,team:state.team,name:state.name,recordType:"personal",totalScore:Number(ev.points||1),note:`${ev.name} 簽到`,createdAt:Date.now(),updatedAt:Date.now()});toast("簽到成功");state.page="home";render()}

function renderMeeting(){const tr=teamRank(),pr=personRank();shell(`<section class="hero" style="text-align:center"><div class="champ-badge">📺 晨會模式</div><div class="champ-name">${tr[0]?.team||"尚無"}</div><div class="champ-score">${tr[0]?.score||0}<small> 分</small></div></section><div class="two"><section class="card"><h2>🏆 團隊戰況</h2>${rankTable(tr,"team").join("")}</section><section class="card"><h2>👑 MVP</h2>${rankTable(pr.slice(0,8),"person").join("")}</section></div>`)}
function renderAdmin(){shell(`<section class="card"><h2>⚙️ 設定管理</h2><div class="admin-grid"><div class="admin-menu"><button class="${state.adminTab==="teams"?"active":""}" data-at="teams">隊伍成員</button><button class="${state.adminTab==="rules"?"active":""}" data-at="rules">分數項目</button><button class="${state.adminTab==="events"?"active":""}" data-at="events">活動 QR</button><button class="${state.adminTab==="activity"?"active":""}" data-at="activity">系統設定</button></div><div id="adminBody"></div></div></section>`);document.querySelectorAll("[data-at]").forEach(b=>b.onclick=()=>{state.adminTab=b.dataset.at;render()});if(state.adminTab==="teams")adminTeams();if(state.adminTab==="rules")adminRules();if(state.adminTab==="events")adminEvents();if(state.adminTab==="activity")adminActivity()}
function adminTeams(){document.getElementById("adminBody").innerHTML=`<div class="form-grid"><input id="newIcon" placeholder="Icon 例如 🐺"><input id="newTeam" placeholder="新增隊伍名稱"></div><button class="btn primary" id="addTeam">新增隊伍</button>${teams().map((t,i)=>`<div class="admin-row"><div class="admin-title">${t.icon} ${t.name}</div><div class="chips">${(t.members||[]).map(m=>`<span class="chip">${m}<button data-rm-m="${i}|${m}">×</button></span>`).join("")}</div><div class="form-grid" style="margin-top:10px"><input id="mem-${i}" placeholder="新增成員"><button class="btn blue" data-add-m="${i}">新增</button></div><button class="btn red" data-rm-t="${i}" style="margin-top:10px">刪除隊伍</button></div>`).join("")}`;document.getElementById("addTeam").onclick=async()=>{const name=document.getElementById("newTeam").value.trim(),icon=document.getElementById("newIcon").value.trim()||"🏆";if(!name)return toast("請輸入隊伍");const cfg=structuredClone(C());cfg.teams.push({id:uid("team"),icon,name,color:"#38bdf8",members:[]});await saveConfig(cfg);toast("已新增")};document.querySelectorAll("[data-add-m]").forEach(b=>b.onclick=async()=>{const i=Number(b.dataset.addM),v=document.getElementById(`mem-${i}`).value.trim();if(!v)return;const cfg=structuredClone(C());cfg.teams[i].members.push(v);await saveConfig(cfg)});document.querySelectorAll("[data-rm-m]").forEach(b=>b.onclick=async()=>{const [i,m]=b.dataset.rmM.split("|"),cfg=structuredClone(C());cfg.teams[Number(i)].members=cfg.teams[Number(i)].members.filter(x=>x!==m);await saveConfig(cfg)});document.querySelectorAll("[data-rm-t]").forEach(b=>b.onclick=async()=>{if(!confirm("刪除隊伍？"))return;const cfg=structuredClone(C());cfg.teams.splice(Number(b.dataset.rmT),1);await saveConfig(cfg)})}
function adminRules(){const block=(type,arr)=>`<h3>${type==="team"?"團隊":"個人"}計分</h3>${arr.map((r,i)=>`<div class="rule-row"><input value="${r.label}" data-label="${type}|${i}"><input type="number" value="${r.points}" data-point="${type}|${i}"><button class="btn red" data-del-rule="${type}|${i}">刪</button></div>`).join("")}<button class="btn blue" data-add-rule="${type}">新增項目</button>`;document.getElementById("adminBody").innerHTML=block("team",teamRules())+block("personal",personalRules())+`<button class="btn primary" id="saveRules" style="width:100%;margin-top:14px">儲存</button>`;document.querySelectorAll("[data-add-rule]").forEach(b=>b.onclick=async()=>{const cfg=structuredClone(C()),arr=b.dataset.addRule==="team"?cfg.teamRules:cfg.personalRules;arr.push({key:uid("rule"),label:"新項目",unit:"次",points:1});await saveConfig(cfg)});document.querySelectorAll("[data-del-rule]").forEach(b=>b.onclick=async()=>{const [t,i]=b.dataset.delRule.split("|"),cfg=structuredClone(C());(t==="team"?cfg.teamRules:cfg.personalRules).splice(Number(i),1);await saveConfig(cfg)});document.getElementById("saveRules").onclick=async()=>{const cfg=structuredClone(C());document.querySelectorAll("[data-label]").forEach(inp=>{const[t,i]=inp.dataset.label.split("|");(t==="team"?cfg.teamRules:cfg.personalRules)[Number(i)].label=inp.value});document.querySelectorAll("[data-point]").forEach(inp=>{const[t,i]=inp.dataset.point.split("|");(t==="team"?cfg.teamRules:cfg.personalRules)[Number(i)].points=Number(inp.value||0)});await saveConfig(cfg);toast("已儲存")}}
function adminEvents(){document.getElementById("adminBody").innerHTML=`<h3>建立活動 QR</h3><div class="form-grid"><input id="evName" placeholder="活動名稱，例如 7/5 晨會"><input id="evPoints" type="number" value="1" placeholder="簽到分數"></div><button class="btn primary" id="addEv">建立活動</button>${events().map((e,i)=>`<div class="admin-row"><div class="admin-title">${e.name}｜簽到 +${e.points}</div><button class="btn blue" data-show-qr="${e.id}">顯示 QR</button><button class="btn red" data-rm-ev="${i}">刪除</button></div>`).join("")}`;document.getElementById("addEv").onclick=async()=>{const name=document.getElementById("evName").value.trim(),points=Number(document.getElementById("evPoints").value||1);if(!name)return toast("請輸入活動名稱");const cfg=structuredClone(C());cfg.events=cfg.events||[];cfg.events.push({id:uid("event"),name,date:new Date().toISOString().slice(0,10),points,active:true});cfg.activity.currentEvent=name;await saveConfig(cfg)};document.querySelectorAll("[data-show-qr]").forEach(b=>b.onclick=()=>{state.page="qr";render()});document.querySelectorAll("[data-rm-ev]").forEach(b=>b.onclick=async()=>{const cfg=structuredClone(C());cfg.events.splice(Number(b.dataset.rmEv),1);await saveConfig(cfg)})}
function adminActivity(){document.getElementById("adminBody").innerHTML=`<label class="field"><span>標題</span><input id="title" value="${activity().title}"></label><label class="field"><span>副標題</span><input id="sub" value="${activity().subtitle}"></label><label class="field"><span>活動名稱</span><input id="cur" value="${activity().currentEvent||""}"></label><label class="field"><span>結束日</span><input type="date" id="end" value="${activity().endDate}"></label><button class="btn primary" id="saveAct">儲存設定</button>`;document.getElementById("saveAct").onclick=async()=>{const cfg=structuredClone(C());cfg.activity={title:document.getElementById("title").value,subtitle:document.getElementById("sub").value,currentEvent:document.getElementById("cur").value,endDate:document.getElementById("end").value};await saveConfig(cfg);toast("已儲存")}}
function exportRows(){csvDownload(`AMR人力特攻隊_${new Date().toISOString().slice(0,10)}.csv`,[["類別","週次","隊伍","姓名","分數","備註","時間"],...state.records.map(r=>[r.recordType,r.week,r.team,r.name,r.totalScore,r.note,r.createdAt?new Date(r.createdAt).toLocaleString("zh-TW"):""])])}
function render(){try{if(state.page==="home")renderHome();else if(state.page==="score")renderScore();else if(state.page==="rank")renderRank();else if(state.page==="person")renderPerson();else if(state.page==="history")renderHistory();else if(state.page==="qr")renderQR();else if(state.page==="checkin")renderCheckin();else if(state.page==="meeting")renderMeeting();else if(state.page==="admin")renderAdmin()}catch(e){app.innerHTML=`<div class="main"><div class="card">系統錯誤：${e.message}</div></div>`;console.error(e)}}
async function boot(){await initFirebase();listenConfig(async cfg=>{if(!cfg){await saveConfig(DEFAULT_CONFIG);state.config=DEFAULT_CONFIG}else state.config=cfg;render()},e=>console.error(e));listenRecords(rows=>{state.records=rows;render()},e=>console.error(e))}
boot();
