
const KEY='amr_v8_alpha_baseline_week_data';
const defaultData={
 settings:{title:'AMR 人力特攻隊',subtitle:'V8 Alpha｜基準週自動推算',baseStart:'2026-07-06',baseEnd:'2026-07-12',showBefore:2,showAfter:5},
 periods:[
  {id:'p1',start:'2026-07-06',end:'2026-07-12'},
  {id:'p2',start:'2026-07-13',end:'2026-07-19'},
  {id:'p3',start:'2026-07-20',end:'2026-07-26'},
  {id:'p4',start:'2026-07-27',end:'2026-08-02'}
 ],
 teams:[
  {id:'t1',name:'五狼攏來隊',members:['天景','小怡君','立維','永朋']},
  {id:'t2',name:'瀚瀚瀚瀚得第一',members:['子瀚','靜萱','陳怡君','雅韻']},
  {id:'t3',name:'盈在起跑點',members:['可盈','恩慈','士誼','奎璿','美如']},
  {id:'t4',name:'陽光委任隊',members:['怡蒨','楚涵','永濂','瑀芯']},
  {id:'t5',name:'你來就隊',members:['巧云','乙榛','圜翰','建宏']}
 ],
 rules:[
  {id:'dream_night',name:'夢想起飛 / 夜創出席',points:2,team:true,personal:false,allowFriends:false,friendPoints:0},
  {id:'friend_dream_night',name:'帶新朋友參加夢想起飛 / 夜創',points:3,team:true,personal:false,allowFriends:true,friendPoints:3},
  {id:'soft_attend',name:'通訊處軟性活動出席',points:2,team:true,personal:false,allowFriends:false,friendPoints:0},
  {id:'friend_soft',name:'帶新朋友參加軟性活動',points:3,team:true,personal:false,allowFriends:true,friendPoints:3},
  {id:'exam_pass',name:'公司考通過',points:3,team:true,personal:false,allowFriends:false,friendPoints:0},
  {id:'contract',name:'登錄 + 簽約',points:10,team:true,personal:false,allowFriends:false,friendPoints:0},
  {id:'excellent',name:'參加優培',points:10,team:true,personal:false,allowFriends:false,friendPoints:0},
  {id:'joint_member',name:'團隊共同運作增員',points:1,team:true,personal:false,allowFriends:false,friendPoints:0},
  {id:'first_touch',name:'網增接觸 / 新增名單 / 約訪',points:1,team:false,personal:true,allowFriends:false,friendPoints:0},
  {id:'soft_cop',name:'緣故約訪 COP / 軟性活動',points:1,team:false,personal:true,allowFriends:false,friendPoints:0},
  {id:'first_interview',name:'初次面談',points:5,team:false,personal:true,allowFriends:false,friendPoints:0},
  {id:'deep_interview',name:'深度面談',points:8,team:false,personal:true,allowFriends:false,friendPoints:0},
  {id:'self_cop',name:'自己參加 COP',points:8,team:false,personal:true,allowFriends:false,friendPoints:0},
  {id:'friend_cop',name:'帶新朋友參加 COP',points:8,team:false,personal:true,allowFriends:true,friendPoints:8}
 ],
 events:[], records:[], deleted:[]
};
let data=load(), page=new URLSearchParams(location.search).get('page')||'home', scoreMode='team', editId=null;
let historyFilter={q:'',period:'',team:''}, statPeriod='';
let scoreState={period:'',team:'',name:'',items:{},manual:0,note:''};
let friendCount=1;

function load(){
 try{
  let x=JSON.parse(localStorage.getItem(KEY));
  if(!x) return structuredClone(defaultData);
  if(!x.settings) x.settings=structuredClone(defaultData.settings);
  if(!x.settings.baseStart) x.settings.baseStart=defaultData.settings.baseStart;
  if(!x.settings.baseEnd) x.settings.baseEnd=defaultData.settings.baseEnd;
  if(!x.settings.showBefore) x.settings.showBefore=2;
  if(!x.settings.showAfter) x.settings.showAfter=5;
  return x;
 }catch(e){return structuredClone(defaultData)}
}
function save(){localStorage.setItem(KEY,JSON.stringify(data))}
function uid(p='id'){return p+'_'+Math.random().toString(36).slice(2,9)}
function now(){return new Date().toLocaleString()}
function today(){return new Date().toISOString().slice(0,10)}
function toast(m){let t=document.createElement('div');t.className='toast';t.textContent=m;document.body.appendChild(t);setTimeout(()=>t.remove(),1800)}
function link(p){return `?page=${p}`}
function go(p){history.pushState(null,'',link(p));page=p;render()} window.go=go;
window.addEventListener('popstate',()=>{page=new URLSearchParams(location.search).get('page')||'home';render()});
function teams(){return data.teams}
function people(){return data.teams.flatMap(t=>t.members.map(m=>({name:m,team:t.name,teamId:t.id})))}
function teamObj(name){return data.teams.find(t=>t.name===name)}
function teamOf(name){let p=people().find(x=>x.name===name);return p?p.team:''}
function members(team){return (teamObj(team)?.members)||[]}
function rule(id){return data.rules.find(r=>r.id===id)||data.rules[0]}
function rulesFor(mode){return data.rules.filter(r=>mode==='team'?r.team:r.personal)}

function parseDate(s){let [y,m,d]=s.split('-').map(Number);return new Date(y,m-1,d)}
function fmtDate(d){return d.toISOString().slice(0,10)}
function addDays(d,n){let x=new Date(d);x.setDate(x.getDate()+n);return x}
function daysBetween(a,b){return Math.floor((parseDate(b)-parseDate(a))/86400000)}
function baseLen(){return Math.max(1,daysBetween(data.settings.baseStart,data.settings.baseEnd)+1)}
function periodByOffset(offset){let len=baseLen(),s=addDays(parseDate(data.settings.baseStart),offset*len),e=addDays(s,len-1);return {id:'w'+offset,offset,start:fmtDate(s),end:fmtDate(e)}}
function currentOffset(){return Math.floor(daysBetween(data.settings.baseStart,today())/baseLen())}
function visiblePeriods(){let cur=currentOffset(),before=Number(data.settings.showBefore||2),after=Number(data.settings.showAfter||5),arr=[];for(let i=cur-before;i<=cur+after;i++)arr.push(periodByOffset(i));return arr}
function periodOfDate(d=today()){return periodByOffset(Math.floor(daysBetween(data.settings.baseStart,d)/baseLen()))}
function periodById(id){return periodByOffset(Number(String(id||'w0').replace('w',''))||0)}
function periodLabel(p){if(!p)return '全部';let clean=s=>s.slice(5).replace(/^0/,'').replace('-','/').replace('/0','/');return `${clean(p.start)}–${clean(p.end)}`}
function periodOptions(sel='',all=false){let opts=visiblePeriods().map(p=>`<option value="${p.id}" ${sel===p.id?'selected':''}>${periodLabel(p)}${p.offset===currentOffset()?'（目前）':''}</option>`).join('');return `${all?'<option value="">全部日期區間</option>':''}${opts}`}

function recordsByPeriod(pid){return !pid?data.records:data.records.filter(r=>r.periodId===pid)}
function activeEvent(){return data.events.find(e=>e.active)||data.events[0]}
function eventRecords(eventId){return data.records.filter(r=>r.eventId===eventId)}
function rankTeams(records=data.records){let m={};teams().forEach(t=>m[t.name]=0);records.forEach(r=>{if(r.team in m)m[r.team]+=Number(r.points||0)});return Object.entries(m).map(([team,score])=>({team,score})).sort((a,b)=>b.score-a.score)}
function rankPeople(records=data.records){let m={};people().forEach(p=>m[p.name]={score:0,team:p.team});records.forEach(r=>{if(!m[r.name])m[r.name]={score:0,team:r.team};m[r.name].score+=Number(r.points||0)});return Object.entries(m).map(([name,x])=>({name,team:x.team,score:x.score})).sort((a,b)=>b.score-a.score)}
function scoreTotal(){let total=Number(scoreState.manual||0);rulesFor(scoreMode).forEach(r=>total+=Number(scoreState.items[r.id]||0)*Number(r.points||0));return total}

function shell(body){document.getElementById('app').innerHTML=hero()+body;nav();bindForms()}
function hero(){return `<section class="hero"><div class="logo"><div class="amr">AMR</div><h1>${data.settings.title.replace('AMR ','')}</h1><p>${data.settings.subtitle}</p></div><div class="topNav">${navLinks()}</div></section>`}
function navLinks(){return [['home','首頁'],['score','積分'],['qr','QR簽到'],['rank','統計'],['admin','管理']].map(x=>`<a href="${link(x[0])}" class="${page===x[0]?'active':''}">${x[1]}</a>`).join('')}
function nav(){document.getElementById('bottomNav').innerHTML=[['home','🏠','首頁'],['score','🏆','積分'],['qr','▣','QR'],['rank','📊','統計'],['admin','⚙️','管理']].map(x=>`<a href="${link(x[0])}" class="${page===x[0]?'active':''}"><span>${x[1]}</span>${x[2]}</a>`).join('')}
document.addEventListener('click',e=>{let a=e.target.closest('a[href^="?page="]');if(!a)return;e.preventDefault();go(new URLSearchParams(a.getAttribute('href').slice(1)).get('page')||'home')},true)

function rows(arr,type){return arr.map((r,i)=>`<div class="row"><div class="medal ${i==0?'one':i==1?'two':i==2?'three':''}">${i+1}</div><div><div class="name">${type==='team'?r.team:r.name}</div><div class="muted">${type==='team'?'團隊':r.team}</div></div><div class="score">${r.score}</div></div>`).join('')||'<div class="empty">尚無資料</div>'}
function home(){let cp=periodOfDate(), rec=recordsByPeriod(cp?.id), tr=rankTeams(rec),pr=rankPeople(rec),todayPts=data.records.filter(r=>String(r.createdDate||'').startsWith(today())).reduce((n,r)=>n+Number(r.points||0),0);shell(`<div class="quick"><a href="?page=score"><span>＋</span>新增積分</a><a href="?page=qr"><span>▣</span>建立 QR</a><a href="?page=rank"><span>📊</span>統計中心</a><a href="?page=admin"><span>⚙️</span>管理中心</a></div><section class="stats"><div class="stat">目前區間<b>${periodLabel(cp)}</b></div><div class="stat">本週冠軍<b>${tr[0]?.team||'尚無'}</b></div><div class="stat">本期 MVP<b>${pr[0]?.name||'尚無'}</b></div><div class="stat">今日新增<b>${todayPts}</b></div></section><section class="card champion"><div class="cup">🏆</div><div class="muted">${periodLabel(cp)}</div><div class="bigName">${tr[0]?.team||'尚無資料'}</div><div class="bigScore">${tr[0]?.score||0}<small> 分</small></div><a class="btn primary" href="?page=rank">查看統計</a></section><div class="grid2"><section class="card"><h2>團隊前三名</h2>${rows(tr.slice(0,3),'team')}</section><section class="card"><h2>個人排行榜</h2>${rows(pr.slice(0,5),'person')}</section></div><section class="card"><h2>最新紀錄</h2>${data.records.slice(-5).reverse().map(recordCard).join('')||'<div class="empty">尚無紀錄</div>'}</section>`)}
function teamOptions(sel=''){return teams().map(t=>`<option value="${t.name}" ${sel===t.name?'selected':''}>${t.name}</option>`).join('')}
function memberOptions(team,sel=''){return members(team).map(m=>`<option value="${m}" ${sel===m?'selected':''}>${m}</option>`).join('')}

function score(){let team=scoreState.team||teams()[0]?.name||'', pid=scoreState.period||periodOfDate()?.id;if(!scoreState.period)scoreState.period=pid;if(!scoreState.team)scoreState.team=team;if(!scoreState.name)scoreState.name=members(team)[0]||'';shell(`<section class="card"><h2>${editId?'修改紀錄':'新增積分'}</h2><div class="tabs"><button class="btn tab ${scoreMode==='team'?'active':''}" onclick="setMode('team')">團隊積分</button><button class="btn tab ${scoreMode==='personal'?'active':''}" onclick="setMode('personal')">個人積分</button></div><form id="scoreForm"><div class="grid3"><label class="field"><span>日期區間</span><select name="period">${periodOptions(pid)}</select></label><label class="field"><span>隊伍</span><select name="team" onchange="changeTeam(this.value)">${teamOptions(team)}</select></label><label class="field"><span>姓名</span><select name="name">${memberOptions(team,scoreState.name)}</select></label></div>${rulesFor(scoreMode).map(r=>`<div class="item"><div class="grid2"><div><div class="name">${r.name}</div><div class="muted">${r.points} 分 / 次</div></div><div class="ctrl"><button type="button" onclick="qty('${r.id}',-1)">−</button><div class="num">${scoreState.items[r.id]||0}</div><button type="button" onclick="qty('${r.id}',1)">＋</button></div></div></div>`).join('')}<label class="field"><span>手動輸入分數</span><input type="number" name="manual" value="${scoreState.manual||0}"></label><label class="field"><span>備註</span><input name="note" value="${scoreState.note||''}" placeholder="可空白"></label><div class="total"><span>本次得分</span><b>${scoreTotal()} 分</b></div><div class="actions"><button class="btn orange wide">${editId?'儲存修改':'送出積分'}</button>${editId?'<button type="button" class="btn" onclick="cancelEdit()">取消修改</button>':''}</div></form></section>${historySection()}`)}
function historySection(){let list=filteredRecords();return `<section class="card"><h2>歷史紀錄</h2><div class="grid3"><label class="field"><span>搜尋姓名/備註/新朋友</span><input value="${historyFilter.q}" oninput="historyFilter.q=this.value;render()" placeholder="搜尋"></label><label class="field"><span>日期區間</span><select onchange="historyFilter.period=this.value;render()">${periodOptions(historyFilter.period,true)}</select></label><label class="field"><span>隊伍</span><select onchange="historyFilter.team=this.value;render()"><option value="">全部隊伍</option>${teams().map(t=>`<option ${historyFilter.team===t.name?'selected':''}>${t.name}</option>`).join('')}</select></label></div>${list.map(recordCard).join('')||'<div class="empty">查無紀錄</div>'}</section>`}
function filteredRecords(){return data.records.filter(r=>(!historyFilter.q||String(r.name+r.note+r.type+(r.friends||[]).map(f=>f.name).join('')).includes(historyFilter.q))&&(!historyFilter.period||r.periodId===historyFilter.period)&&(!historyFilter.team||r.team===historyFilter.team)).slice().reverse()}
function recordCard(r){let fs=(r.friends||[]).map(f=>f.name).filter(Boolean).join('、');return `<div class="item"><div class="name">${r.name}｜+${r.points} 分</div><div class="muted">${periodLabel(periodById(r.periodId))}｜${r.team}｜${r.date}｜${r.note||r.type}${fs?'｜新朋友：'+fs:''}</div><div class="actions"><button class="btn small blue" onclick="viewRecord('${r.id}')">查看</button><button class="btn small primary" onclick="editRecord('${r.id}')">修改</button><button class="btn small red" onclick="delRecord('${r.id}')">刪除</button></div></div>`}
window.setMode=m=>{scoreMode=m;scoreState.items={};render()}
window.changeTeam=t=>{scoreState.team=t;scoreState.name=members(t)[0]||'';render()}
window.qty=(id,n)=>{scoreState.items[id]=Math.max(0,Number(scoreState.items[id]||0)+n);render()}
window.cancelEdit=()=>{editId=null;scoreState={period:periodOfDate()?.id,team:'',name:'',items:{},manual:0,note:''};render()}

function qr(){let ev=activeEvent();let url=ev?location.origin+location.pathname+`?page=checkin&id=${ev.id}`:'';shell(`<section class="card"><h2>建立活動 QR</h2><form id="eventForm"><div class="grid3"><label class="field"><span>日期區間</span><select name="period">${periodOptions(periodOfDate()?.id)}</select></label><label class="field"><span>活動類型</span><select name="type">${data.rules.map(r=>`<option value="${r.id}">${r.name}（${r.points}分）</option>`).join('')}</select></label><label class="field"><span>活動日期</span><input type="date" name="date" value="${today()}"></label></div><label class="field"><span>活動名稱</span><input name="name" placeholder="例如：夢想起飛"></label><button class="btn primary wide">建立活動</button></form></section><section class="card"><h2>目前 QR</h2>${ev?`<div class="qrbox"><p>${ev.name}</p><div class="muted">${periodLabel(periodById(ev.periodId))}</div><img src="https://api.qrserver.com/v1/create-qr-code/?size=320x320&data=${encodeURIComponent(url)}"><div class="actions" style="justify-content:center"><button class="btn primary" onclick="copyText('${url}')">複製連結</button><a class="btn" href="?page=checkin&id=${ev.id}">直接測試簽到</a></div></div>`:'<div class="empty">尚無活動</div>'}</section>${ev?attendanceTable(ev):''}<section class="card"><h2>活動列表</h2>${data.events.map(e=>`<div class="item"><div class="name">${e.name}</div><div class="muted">${periodLabel(periodById(e.periodId))}｜${rule(e.type).name}｜${rule(e.type).points}分｜${e.active?'目前使用':'待用'}</div><div class="actions"><button class="btn small primary" onclick="setActive('${e.id}')">設為目前</button><button class="btn small red" onclick="delEvent('${e.id}')">刪除</button></div></div>`).join('')||'<div class="empty">尚無活動</div>'}</section>`)}
function attendanceTable(ev){let recs=eventRecords(ev.id), signed=new Set(recs.map(r=>r.name));let rowsHtml=people().map(p=>{let r=recs.find(x=>x.name===p.name), fs=(r?.friends||[]).map(f=>f.name).filter(Boolean).join('、');return `<tr><td>${r?'✅':'❌'}</td><td>${p.team}</td><td>${p.name}</td><td class="hideM">${r?r.date:'未簽'}</td><td>${fs||'-'}</td><td>${r?('+'+r.points):'-'}</td><td>${r?`<button class="btn small primary" onclick="editRecord('${r.id}')">修改</button>`:`<button class="btn small green" onclick="manualCheckin('${ev.id}','${p.name}')">補簽</button>`}</td></tr>`}).join('');return `<section class="card"><h2>簽到管理｜${ev.name}</h2><div class="muted">${periodLabel(periodById(ev.periodId))}</div><div class="stats"><div class="stat">應到<b>${people().length}</b></div><div class="stat">已到<b>${signed.size}</b></div><div class="stat">未到<b>${people().length-signed.size}</b></div><div class="stat">發出積分<b>${recs.reduce((n,r)=>n+Number(r.points||0),0)}</b></div></div><div class="tableWrap"><table class="table"><thead><tr><th>狀態</th><th>隊伍</th><th>姓名</th><th class="hideM">時間</th><th>新朋友</th><th>分數</th><th>操作</th></tr></thead><tbody>${rowsHtml}</tbody></table></div></section>`}

function checkin(){let id=new URLSearchParams(location.search).get('id'),ev=data.events.find(e=>e.id===id)||activeEvent();if(!ev)return shell('<section class="card"><h2>找不到活動</h2><p class="muted">請回 QR 頁重新建立活動。</p><a class="btn primary" href="?page=qr">回 QR 頁</a></section>');let r=rule(ev.type);friendCount=1;shell(`<section class="card"><h2>${ev.name}</h2><p class="muted">${periodLabel(periodById(ev.periodId))}｜簽到自動 +${r.points} 分${r.allowFriends?`｜新朋友 +${r.friendPoints||r.points} / 位`:''}</p><form id="checkinForm" data-event="${ev.id}"><label class="field"><span>隊伍</span><select name="team" onchange="renderCheckinMembers(this.value)">${teamOptions(teams()[0]?.name)}</select></label><label class="field"><span>姓名</span><select name="name" id="checkinName">${memberOptions(teams()[0]?.name)}</select></label>${r.allowFriends?friendInputs():''}<button class="btn primary wide">完成簽到</button></form></section>`)}
function friendInputs(){let html=`<h3>新朋友名單</h3><div id="friendsArea">`;for(let i=1;i<=friendCount;i++){html+=`<div class="friendBox"><label class="field"><span>新朋友 ${i} 姓名</span><input name="friendName${i}" placeholder="可空白"></label><label class="field"><span>新朋友 ${i} 電話（可選）</span><input name="friendPhone${i}" placeholder="可空白"></label></div>`}return html+`</div><button class="btn small" type="button" onclick="addFriend()">＋新增新朋友</button>`}
window.addFriend=()=>{friendCount++;render()}
window.renderCheckinMembers=t=>{document.getElementById('checkinName').innerHTML=memberOptions(t)}

function rank(){let pid=statPeriod||periodOfDate()?.id, rec=recordsByPeriod(pid), tr=rankTeams(rec), pr=rankPeople(rec);shell(`<section class="card"><h2>統計中心</h2><label class="field"><span>日期區間</span><select onchange="statPeriod=this.value;render()">${periodOptions(pid,true)}</select></label><div class="stats"><div class="stat">總分<b>${rec.reduce((n,r)=>n+Number(r.points||0),0)}</b></div><div class="stat">紀錄數<b>${rec.length}</b></div><div class="stat">新朋友<b>${rec.reduce((n,r)=>n+(r.friends||[]).length,0)}</b></div><div class="stat">第一名<b>${tr[0]?.team||'尚無'}</b></div></div></section><div class="grid2"><section class="card"><h2>團隊排行榜</h2>${rows(tr,'team')}</section><section class="card"><h2>個人排行榜</h2>${rows(pr,'person')}</section></div><section class="card"><h2>積分總表</h2>${teamSummary(rec)}</section><section class="card"><h2>積分流水帳</h2>${rec.slice().reverse().map(recordCard).join('')||'<div class="empty">尚無紀錄</div>'}</section>`)}
function teamSummary(rec){return teams().map(t=>{let mem=t.members.map(m=>({name:m,score:rec.filter(r=>r.name===m).reduce((n,r)=>n+Number(r.points||0),0)})).sort((a,b)=>b.score-a.score);let total=mem.reduce((n,x)=>n+x.score,0);return `<div class="item"><div class="name">${t.name}｜${total} 分</div>${mem.map(x=>`<div class="row"><div class="medal">👤</div><div><div class="name">${x.name}</div><div class="muted">${t.name}</div></div><div class="score">${x.score}</div></div>`).join('')}</div>`}).join('')}

function admin(){shell(`<section class="card"><h2>管理中心</h2><div class="grid2"><section><h3>基準週設定</h3><form id="baseForm"><div class="grid2"><label class="field"><span>基準開始日</span><input type="date" name="baseStart" value="${data.settings.baseStart}"></label><label class="field"><span>基準結束日</span><input type="date" name="baseEnd" value="${data.settings.baseEnd}"></label></div><div class="grid2"><label class="field"><span>前面顯示幾週</span><input type="number" name="showBefore" value="${data.settings.showBefore||2}"></label><label class="field"><span>後面顯示幾週</span><input type="number" name="showAfter" value="${data.settings.showAfter||5}"></label></div><button class="btn orange wide">儲存基準週</button><p class="muted">設定一次基準週，系統會自動往前、往後推算日期區間。</p></form><h3>目前可選區間</h3>${visiblePeriods().map(p=>`<div class="item"><div class="name">${periodLabel(p)}${p.offset===currentOffset()?'（目前）':''}</div></div>`).join('')}${data.periods.map(p=>`<div class="item"><div class="name">${periodLabel(p)}</div><div class="actions"><button class="btn small red" onclick="delPeriod('${p.id}')">刪除</button></div></div>`).join('')}</section><section><h3>隊伍管理</h3><form id="teamForm"><label class="field"><span>新增隊伍</span><input name="team"></label><button class="btn primary">新增隊伍</button></form>${data.teams.map(t=>`<div class="item"><div class="name">${t.name}</div><div class="muted">${t.members.length}人</div><div class="actions"><button class="btn small blue" onclick="renameTeam('${t.id}')">改名</button><button class="btn small red" onclick="delTeam('${t.id}')">刪除</button></div></div>`).join('')}</section></div><section><h3>成員管理</h3><form id="memberForm"><div class="grid2"><label class="field"><span>隊伍</span><select name="team">${data.teams.map(t=>`<option value="${t.id}">${t.name}</option>`).join('')}</select></label><label class="field"><span>姓名</span><input name="name"></label></div><button class="btn primary">新增成員</button></form>${people().map(p=>`<span class="pill">${p.team}｜${p.name}</span>`).join('')}</section></section><section class="card"><h2>積分規則</h2>${data.rules.map(r=>`<div class="item"><div class="name">${r.name}</div><div class="grid3"><label class="field"><span>分數</span><input type="number" value="${r.points}" onchange="updateRule('${r.id}','points',this.value)"></label><label class="field"><span>新朋友分數</span><input type="number" value="${r.friendPoints||0}" onchange="updateRule('${r.id}','friendPoints',this.value)"></label><label class="field"><span>項目名稱</span><input value="${r.name}" onchange="updateRule('${r.id}','name',this.value)"></label></div></div>`).join('')}</section><section class="card"><h2>資料管理</h2><div class="actions"><button class="btn red" onclick="resetAll()">重設全部資料</button></div></section>`)}
function bindForms(){let f=document.getElementById('scoreForm');if(f)f.onsubmit=e=>{e.preventDefault();let fd=new FormData(f);scoreState.period=fd.get('period');scoreState.team=fd.get('team');scoreState.name=fd.get('name');scoreState.manual=Number(fd.get('manual')||0);scoreState.note=fd.get('note')||'';let total=scoreTotal();if(total===0)return toast('本次得分為 0');let rec={id:editId||uid('rec'),date:now(),createdDate:today(),updatedAt:editId?now():undefined,periodId:scoreState.period,team:scoreState.team,name:scoreState.name,mode:scoreMode,items:structuredClone(scoreState.items),manual:scoreState.manual,points:total,note:scoreState.note||'手動積分',type:scoreMode==='team'?'團隊積分':'個人積分'};if(editId){let i=data.records.findIndex(x=>x.id===editId);if(i>=0)data.records[i]={...data.records[i],...rec};editId=null}else data.records.push(rec);scoreState={period:scoreState.period,team:scoreState.team,name:scoreState.name,items:{},manual:0,note:''};save();toast('已儲存');go('home')};let ef=document.getElementById('eventForm');if(ef)ef.onsubmit=e=>{e.preventDefault();let fd=new FormData(ef),r=rule(fd.get('type'));data.events.forEach(x=>x.active=false);data.events.push({id:uid('ev'),name:fd.get('name')||r.name,type:r.id,periodId:fd.get('period'),date:fd.get('date'),active:true,createdAt:now()});save();toast('活動已建立');go('qr')};let cf=document.getElementById('checkinForm');if(cf)cf.onsubmit=e=>{e.preventDefault();let fd=new FormData(cf),ev=data.events.find(x=>x.id===cf.dataset.event),name=fd.get('name');let friends=[];for(let i=1;i<=friendCount;i++){let fn=(fd.get('friendName'+i)||'').trim(),ph=(fd.get('friendPhone'+i)||'').trim();if(fn)friends.push({name:fn,phone:ph})}checkinMember(ev.id,name,friends,'QR簽到')};let tf=document.getElementById('teamForm');if(tf)tf.onsubmit=e=>{e.preventDefault();let v=new FormData(tf).get('team');if(v){data.teams.push({id:uid('t'),name:v,members:[]});save();render()}};let mf=document.getElementById('memberForm');if(mf)mf.onsubmit=e=>{e.preventDefault();let fd=new FormData(mf),t=data.teams.find(x=>x.id===fd.get('team'));if(t&&fd.get('name')){t.members.push(fd.get('name'));save();render()}};let bf=document.getElementById('baseForm');if(bf)bf.onsubmit=e=>{e.preventDefault();let fd=new FormData(bf);data.settings.baseStart=fd.get('baseStart');data.settings.baseEnd=fd.get('baseEnd');data.settings.showBefore=Number(fd.get('showBefore')||2);data.settings.showAfter=Number(fd.get('showAfter')||5);save();toast('基準週已更新');render()};let pf=document.getElementById('periodForm');if(pf)pf.onsubmit=e=>{e.preventDefault();let fd=new FormData(pf);if(fd.get('start')&&fd.get('end')){data.periods.push({id:uid('p'),start:fd.get('start'),end:fd.get('end')});save();render()}}}
function checkinMember(eventId,name,friends=[],source='補簽'){let ev=data.events.find(x=>x.id===eventId),r=rule(ev.type);if(data.records.some(x=>x.eventId===eventId&&x.name===name))return toast('此活動已簽到');let pts=Number(r.points||0)+Number(friends.length||0)*Number(r.friendPoints||r.points||0);data.records.push({id:uid('rec'),eventId,date:now(),createdDate:today(),periodId:ev.periodId,team:teamOf(name),name,mode:'team',type:r.name,points:pts,friends,note:`${ev.name}｜${source}`,items:{[r.id]:1},manual:0});save();toast('簽到成功');go('home')}
window.manualCheckin=(eventId,name)=>checkinMember(eventId,name,[],'管理員補簽')
window.delRecord=id=>{let i=data.records.findIndex(r=>r.id===id);if(i>=0&&confirm('刪除此紀錄？')){data.deleted.push({...data.records[i],deletedAt:now()});data.records.splice(i,1);save();render()}}
window.viewRecord=id=>{let r=data.records.find(x=>x.id===id);if(r){let fs=(r.friends||[]).map(f=>`${f.name}${f.phone?'（'+f.phone+'）':''}`).join('、');alert(`姓名：${r.name}\n隊伍：${r.team}\n日期區間：${periodLabel(periodById(r.periodId))}\n分數：${r.points}\n新朋友：${fs||'無'}\n備註：${r.note}\n日期：${r.date}`)}}
window.editRecord=id=>{let r=data.records.find(x=>x.id===id);if(!r)return;editId=id;scoreMode=r.mode||'team';scoreState={period:r.periodId||periodOfDate()?.id,team:r.team,name:r.name,items:structuredClone(r.items||{}),manual:Number(r.manual||0),note:r.note||''};go('score')}
window.setActive=id=>{data.events.forEach(e=>e.active=e.id===id);save();render()}
window.delEvent=id=>{if(confirm('刪除活動？')){data.events=data.events.filter(e=>e.id!==id);save();render()}}
window.copyText=async t=>{try{await navigator.clipboard.writeText(t);toast('已複製')}catch(e){prompt('複製連結',t)}}
window.delTeam=id=>{if(confirm('刪除隊伍？')){data.teams=data.teams.filter(t=>t.id!==id);save();render()}}
window.renameTeam=id=>{let t=data.teams.find(x=>x.id===id),v=prompt('隊伍名稱',t.name);if(v){t.name=v;save();render()}}
window.delPeriod=id=>{if(confirm('刪除日期區間？')){data.periods=data.periods.filter(p=>p.id!==id);save();render()}}
window.updateRule=(id,key,v)=>{let r=rule(id);r[key]=key==='points'||key==='friendPoints'?Number(v||0):v;save();toast('已更新')}
window.resetAll=()=>{if(confirm('確定重設全部資料？')){data=structuredClone(defaultData);save();render()}}
function render(){if(page==='home')home();else if(page==='score')score();else if(page==='qr')qr();else if(page==='checkin')checkin();else if(page==='rank')rank();else if(page==='admin')admin();else home()}
render();