
const KEY='amr_v74_stable_data';
const defaultData={
 settings:{title:'AMR 人力特攻隊',subtitle:'團結・合作・突破・共創榮耀'},
 teams:[
  {id:'t1',name:'五狼攏來隊',members:['天景','小怡君','立維','永朋']},
  {id:'t2',name:'瀚瀚瀚瀚得第一',members:['子瀚','靜萱','陳怡君','雅韻']},
  {id:'t3',name:'盈在起跑點',members:['可盈','恩慈','士誼','奎璿','美如']},
  {id:'t4',name:'陽光委任隊',members:['怡蒨','楚涵','永濂','瑀芯']},
  {id:'t5',name:'你來就隊',members:['巧云','乙榛','圜翰','建宏']}
 ],
 rules:[
  {id:'amr',name:'AMR例會',points:0,attendanceOnly:true,allowFriends:false},
  {id:'night',name:'夜創',points:2,attendanceOnly:false,allowFriends:true,friendPoints:3},
  {id:'dream',name:'夢想起飛',points:2,attendanceOnly:false,allowFriends:true,friendPoints:3},
  {id:'soft',name:'軟性活動',points:2,attendanceOnly:false,allowFriends:true,friendPoints:3},
  {id:'contract',name:'登錄 + 簽約',points:10,attendanceOnly:false,allowFriends:false}
 ],
 events:[],
 records:[]
};
let data=load(), page=new URLSearchParams(location.search).get('page')||'home';
function load(){try{return JSON.parse(localStorage.getItem(KEY))||structuredClone(defaultData)}catch(e){return structuredClone(defaultData)}}
function save(){localStorage.setItem(KEY,JSON.stringify(data))}
function uid(p='id'){return p+'_'+Math.random().toString(36).slice(2,9)}
function today(){return new Date().toISOString().slice(0,10)}
function toast(m){let t=document.createElement('div');t.className='toast';t.textContent=m;document.body.appendChild(t);setTimeout(()=>t.remove(),1800)}
function link(p){return `?page=${p}`}
function go(p){history.pushState(null,'',link(p));page=p;render()} window.go=go;
window.addEventListener('popstate',()=>{page=new URLSearchParams(location.search).get('page')||'home';render()});
function people(){return data.teams.flatMap(t=>t.members.map(m=>({name:m,team:t.name})))}
function teamOf(name){let p=people().find(x=>x.name===name);return p?p.team:''}
function rule(id){return data.rules.find(r=>r.id===id)||data.rules[0]}
function activeEvent(){return data.events.find(e=>e.active)||data.events[0]}
function rankTeams(){let m={};data.teams.forEach(t=>m[t.name]=0);data.records.forEach(r=>{if(r.team in m)m[r.team]+=Number(r.points||0)});return Object.entries(m).map(([team,score])=>({team,score})).sort((a,b)=>b.score-a.score)}
function rankPeople(){let m={};people().forEach(p=>m[p.name]={score:0,team:p.team});data.records.forEach(r=>{if(!m[r.name])m[r.name]={score:0,team:r.team};m[r.name].score+=Number(r.points||0)});return Object.entries(m).map(([name,x])=>({name,team:x.team,score:x.score})).sort((a,b)=>b.score-a.score)}
function shell(body){document.getElementById('app').innerHTML=hero()+body;nav();bindForms()}
function hero(){return `<section class="hero"><div class="logo"><div class="amr">AMR</div><h1>${data.settings.title.replace('AMR ','')}</h1><p>${data.settings.subtitle}</p></div><div class="topNav">${navLinks()}</div></section>`}
function navLinks(){return [['home','首頁'],['score','積分'],['qr','QR簽到'],['rank','排行榜'],['admin','管理']].map(x=>`<a href="${link(x[0])}" class="${page===x[0]?'active':''}">${x[1]}</a>`).join('')}
function nav(){document.getElementById('bottomNav').innerHTML=[['home','🏠','首頁'],['score','🏆','積分'],['qr','▣','QR'],['rank','👑','排行'],['admin','⚙️','管理']].map(x=>`<a href="${link(x[0])}" class="${page===x[0]?'active':''}"><span>${x[1]}</span>${x[2]}</a>`).join('')}
document.addEventListener('click',e=>{let a=e.target.closest('a[href^="?page="]');if(!a)return;e.preventDefault();go(new URLSearchParams(a.getAttribute('href').slice(1)).get('page')||'home')},true)
function rows(arr,type){return arr.map((r,i)=>`<div class="row"><div class="medal ${i==0?'one':i==1?'two':i==2?'three':''}">${i+1}</div><div><div class="name">${type==='team'?r.team:r.name}</div><div class="muted">${type==='team'?'團隊':r.team}</div></div><div class="score">${r.score}</div></div>`).join('')||'<div class="empty">尚無資料</div>'}
function home(){let tr=rankTeams(),pr=rankPeople(),todayPts=data.records.filter(r=>String(r.date).startsWith(today())).reduce((n,r)=>n+Number(r.points||0),0);shell(`<div class="quick"><a href="?page=score"><span>＋</span>新增積分</a><a href="?page=qr"><span>▣</span>建立 QR</a><a href="?page=rank"><span>👑</span>排行榜</a><a href="?page=admin"><span>⚙️</span>管理中心</a></div><section class="stats"><div class="stat">目前冠軍<b>${tr[0]?.team||'尚無'}</b></div><div class="stat">本期 MVP<b>${pr[0]?.name||'尚無'}</b></div><div class="stat">今日新增<b>${todayPts}</b></div><div class="stat">團隊數<b>${data.teams.length}</b></div></section><section class="card champion"><div class="cup">🏆</div><div class="bigName">${tr[0]?.team||'尚無資料'}</div><div class="bigScore">${tr[0]?.score||0}<small> 分</small></div></section><div class="grid2"><section class="card"><h2>團隊前三名</h2>${rows(tr.slice(0,3),'team')}</section><section class="card"><h2>個人排行榜</h2>${rows(pr.slice(0,5),'person')}</section></div><section class="card"><h2>最新紀錄</h2>${data.records.slice(-5).reverse().map(r=>`<div class="row"><div class="medal">＋</div><div><div class="name">${r.name}</div><div class="muted">${r.note||r.type}｜${r.team}</div></div><div class="score">${r.points}</div></div>`).join('')||'<div class="empty">尚無紀錄</div>'}</section>`)}
function memberOptions(sel=''){return people().map(p=>`<option value="${p.name}" ${sel===p.name?'selected':''}>${p.team}｜${p.name}</option>`).join('')}
function score(){shell(`<section class="card"><h2>新增積分</h2><form id="scoreForm"><label class="field"><span>成員</span><select name="name">${memberOptions()}</select></label><label class="field"><span>加分項目</span><select name="type">${data.rules.filter(r=>!r.attendanceOnly).map(r=>`<option value="${r.id}">${r.name}（${r.points}分）</option>`).join('')}</select></label><label class="field"><span>備註</span><input name="note" placeholder="可空白"></label><button class="btn primary" style="width:100%">送出加分</button></form></section><section class="card"><h2>積分紀錄</h2>${data.records.slice().reverse().map(r=>`<div class="item"><div class="name">${r.name} +${r.points}</div><div class="muted">${r.date}｜${r.note||r.type}｜${r.team}</div><div class="actions"><button class="btn small red" onclick="delRecord('${r.id}')">刪除</button></div></div>`).join('')||'<div class="empty">尚無紀錄</div>'}</section>`)}
function qr(){let ev=activeEvent();let url=ev?location.origin+location.pathname+`?page=checkin&id=${ev.id}`:'';shell(`<section class="card"><h2>建立活動 QR</h2><form id="eventForm"><label class="field"><span>活動類型</span><select name="type">${data.rules.map(r=>`<option value="${r.id}">${r.name}（${r.points}分）</option>`).join('')}</select></label><label class="field"><span>活動名稱</span><input name="name" placeholder="例如：7/10 夢想起飛"></label><button class="btn primary" style="width:100%">建立活動</button></form></section><section class="card"><h2>目前 QR</h2>${ev?`<div class="qrbox"><p>${ev.name}</p><img src="https://api.qrserver.com/v1/create-qr-code/?size=320x320&data=${encodeURIComponent(url)}"><div class="actions" style="justify-content:center"><button class="btn primary" onclick="copyText('${url}')">複製連結</button><a class="btn" href="?page=checkin&id=${ev.id}">直接測試簽到</a></div></div>`:'<div class="empty">尚無活動</div>'}</section><section class="card"><h2>活動列表</h2>${data.events.map(e=>`<div class="item"><div class="name">${e.name}</div><div class="muted">${rule(e.type).name}｜${rule(e.type).points}分｜${e.active?'目前使用':'待用'}</div><div class="actions"><button class="btn small primary" onclick="setActive('${e.id}')">設為目前</button><button class="btn small red" onclick="delEvent('${e.id}')">刪除</button></div></div>`).join('')||'<div class="empty">尚無活動</div>'}</section>`)}
function checkin(){let id=new URLSearchParams(location.search).get('id'),ev=data.events.find(e=>e.id===id)||activeEvent();if(!ev)return shell('<section class="card"><h2>找不到活動</h2></section>');let r=rule(ev.type);shell(`<section class="card"><h2>${ev.name}</h2><p class="muted">${r.attendanceOnly?'AMR 只簽到不加分':`簽到自動 +${r.points} 分`}</p><form id="checkinForm" data-event="${ev.id}"><label class="field"><span>成員</span><select name="name">${memberOptions()}</select></label>${r.allowFriends?`<label class="field"><span>新朋友人數</span><input type="number" name="friends" value="0" min="0"></label>`:''}<button class="btn primary" style="width:100%">完成簽到</button></form></section>`)}
function rank(){shell(`<section class="card"><h2>團隊排行</h2>${rows(rankTeams(),'team')}</section><section class="card"><h2>個人排行</h2>${rows(rankPeople(),'person')}</section>`)}
function admin(){shell(`<section class="card"><h2>管理中心</h2><div class="grid2"><section><h3>隊伍</h3><form id="teamForm"><label class="field"><span>新增隊伍</span><input name="team"></label><button class="btn primary">新增隊伍</button></form>${data.teams.map(t=>`<div class="item"><div class="name">${t.name}</div><div class="muted">${t.members.length}人</div><div class="actions"><button class="btn small red" onclick="delTeam('${t.id}')">刪除隊伍</button></div></div>`).join('')}</section><section><h3>成員</h3><form id="memberForm"><label class="field"><span>隊伍</span><select name="team">${data.teams.map(t=>`<option value="${t.id}">${t.name}</option>`).join('')}</select></label><label class="field"><span>姓名</span><input name="name"></label><button class="btn primary">新增成員</button></form></section></div></section><section class="card"><h2>積分規則</h2>${data.rules.map(r=>`<div class="item"><div class="name">${r.name}</div><label class="field"><span>分數</span><input type="number" value="${r.points}" onchange="updateRule('${r.id}',this.value)"></label></div>`).join('')}</section><section class="card"><h2>資料管理</h2><div class="actions"><button class="btn red" onclick="resetAll()">重設全部資料</button></div></section>`)}
function bindForms(){let f=document.getElementById('scoreForm');if(f)f.onsubmit=e=>{e.preventDefault();let fd=new FormData(f),name=fd.get('name'),r=rule(fd.get('type'));data.records.push({id:uid('rec'),date:new Date().toLocaleString(),name,team:teamOf(name),type:r.name,points:r.points,note:fd.get('note')||r.name});save();toast('加分成功');go('home')};let ef=document.getElementById('eventForm');if(ef)ef.onsubmit=e=>{e.preventDefault();let fd=new FormData(ef),r=rule(fd.get('type'));data.events.forEach(x=>x.active=false);data.events.push({id:uid('ev'),name:fd.get('name')||r.name,type:r.id,active:true,date:new Date().toLocaleString()});save();toast('活動已建立');go('qr')};let cf=document.getElementById('checkinForm');if(cf)cf.onsubmit=e=>{e.preventDefault();let fd=new FormData(cf),ev=data.events.find(x=>x.id===cf.dataset.event),r=rule(ev.type),name=fd.get('name');let already=data.records.some(x=>x.eventId===ev.id&&x.name===name);if(already)return toast('此活動已簽到');let friends=Number(fd.get('friends')||0),pts=r.attendanceOnly?0:r.points+friends*Number(r.friendPoints||0);data.records.push({id:uid('rec'),eventId:ev.id,date:new Date().toLocaleString(),name,team:teamOf(name),type:r.name,points:pts,note:ev.name+(friends?`｜新朋友${friends}位`:''),friends});save();toast('簽到成功');go('home')};let tf=document.getElementById('teamForm');if(tf)tf.onsubmit=e=>{e.preventDefault();let v=new FormData(tf).get('team');if(v){data.teams.push({id:uid('t'),name:v,members:[]});save();render()}};let mf=document.getElementById('memberForm');if(mf)mf.onsubmit=e=>{e.preventDefault();let fd=new FormData(mf),t=data.teams.find(x=>x.id===fd.get('team'));if(t&&fd.get('name')){t.members.push(fd.get('name'));save();render()}}}
window.delRecord=id=>{data.records=data.records.filter(r=>r.id!==id);save();render()}
window.setActive=id=>{data.events.forEach(e=>e.active=e.id===id);save();render()}
window.delEvent=id=>{data.events=data.events.filter(e=>e.id!==id);save();render()}
window.copyText=async t=>{await navigator.clipboard.writeText(t);toast('已複製')}
window.delTeam=id=>{if(confirm('刪除隊伍？')){data.teams=data.teams.filter(t=>t.id!==id);save();render()}}
window.updateRule=(id,v)=>{let r=rule(id);r.points=Number(v||0);save();toast('已更新')}
window.resetAll=()=>{if(confirm('確定重設全部資料？')){data=structuredClone(defaultData);save();render()}}
function render(){if(page==='home')home();else if(page==='score')score();else if(page==='qr')qr();else if(page==='checkin')checkin();else if(page==='rank')rank();else if(page==='admin')admin();else home()}
render();
